-- Run this in the Supabase SQL Editor to set up your tables

CREATE TABLE IF NOT EXISTS guild_configs (
  guild_id TEXT PRIMARY KEY,
  prefix TEXT DEFAULT ',',
  log_channel TEXT,
  welcome_channel TEXT,
  welcome_message TEXT,
  level_channel TEXT,
  ticket_category TEXT,
  autorole_id TEXT,
  staff_role TEXT,
  goodbye_channel TEXT,
  goodbye_message TEXT,
  boost_channel TEXT,
  boost_message TEXT,
  voicemaster_channel TEXT,
  voicemaster_category TEXT,
  antinuke_enabled INTEGER DEFAULT 0,
  antiraid_enabled INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS users (
  user_id TEXT,
  guild_id TEXT,
  balance INTEGER DEFAULT 0,
  bank INTEGER DEFAULT 0,
  xp INTEGER DEFAULT 0,
  level INTEGER DEFAULT 0,
  last_daily INTEGER DEFAULT 0,
  last_work INTEGER DEFAULT 0,
  last_rob INTEGER DEFAULT 0,
  PRIMARY KEY (user_id, guild_id)
);

CREATE TABLE IF NOT EXISTS tickets (
  ticket_id TEXT PRIMARY KEY,
  guild_id TEXT,
  user_id TEXT,
  channel_id TEXT,
  closed INTEGER DEFAULT 0,
  transcript TEXT,
  anonymous INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS economy (
  user_id TEXT PRIMARY KEY,
  balance INTEGER DEFAULT 0,
  bank INTEGER DEFAULT 0,
  last_daily INTEGER DEFAULT 0,
  last_work INTEGER DEFAULT 0,
  last_rob INTEGER DEFAULT 0,
  rules_accepted INTEGER DEFAULT 0,
  partner_id TEXT,
  bio TEXT,
  marriage_time INTEGER,
  parent_id TEXT,
  children TEXT
);

CREATE TABLE IF NOT EXISTS inventory (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT,
  item_id TEXT,
  count INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS giveaways (
  message_id TEXT PRIMARY KEY,
  guild_id TEXT,
  channel_id TEXT,
  prize TEXT,
  winners INTEGER,
  end_time INTEGER,
  ended INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS warns (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  guild_id TEXT,
  user_id TEXT,
  reason TEXT,
  timestamp INTEGER
);

CREATE TABLE IF NOT EXISTS logs (
  guild_id TEXT,
  event TEXT,
  channel_id TEXT,
  PRIMARY KEY (guild_id, event)
);

CREATE TABLE IF NOT EXISTS fake_permissions (
  guild_id TEXT,
  role_id TEXT,
  permission TEXT,
  PRIMARY KEY (guild_id, role_id, permission)
);

CREATE TABLE IF NOT EXISTS invokes (
  guild_id TEXT,
  command TEXT,
  message TEXT,
  PRIMARY KEY (guild_id, command)
);

CREATE TABLE IF NOT EXISTS aliases (
  guild_id TEXT,
  alias TEXT,
  command TEXT,
  PRIMARY KEY (guild_id, alias)
);

CREATE TABLE IF NOT EXISTS automod (
  guild_id TEXT PRIMARY KEY,
  links INTEGER DEFAULT 0,
  invites INTEGER DEFAULT 0,
  mass_mentions INTEGER DEFAULT 0,
  bad_words INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS reaction_roles (
  message_id TEXT,
  guild_id TEXT,
  channel_id TEXT,
  emoji TEXT,
  role_id TEXT,
  PRIMARY KEY (message_id, emoji)
);
