-- Run this in the Supabase SQL Editor to set up your tables

-- 1. Guild Configs
CREATE TABLE IF NOT EXISTS guild_configs (
  guild_id TEXT PRIMARY KEY,
  prefix TEXT DEFAULT ',',
  log_channel TEXT,
  welcome_channel TEXT,
  welcome_message TEXT,
  level_channel TEXT,
  ticket_category TEXT,
  autorole_id TEXT,
  staff_role TEXT,
  goodbye_channel TEXT,
  goodbye_message TEXT,
  boost_channel TEXT,
  boost_message TEXT,
  voicemaster_channel TEXT,
  voicemaster_category TEXT,
  antinuke_enabled INTEGER DEFAULT 0,
  antiraid_enabled INTEGER DEFAULT 0
);

-- 2. Users (Leveling & Guild Data)
-- Note: Supabase/Postgres has composite primary keys support.
CREATE TABLE IF NOT EXISTS users (
  user_id TEXT,
  guild_id TEXT,
  xp INTEGER DEFAULT 0,
  level INTEGER DEFAULT 0,
  PRIMARY KEY (user_id, guild_id)
);

-- 3. Tickets (Relational Link to guild_configs optional but good practice)
CREATE TABLE IF NOT EXISTS tickets (
  ticket_id TEXT PRIMARY KEY,
  guild_id TEXT REFERENCES guild_configs(guild_id) ON DELETE CASCADE,
  user_id TEXT,
  channel_id TEXT,
  closed INTEGER DEFAULT 0,
  transcript TEXT,
  anonymous INTEGER DEFAULT 0
);

-- 4. Global Economy Profile
CREATE TABLE IF NOT EXISTS economy (
  user_id TEXT PRIMARY KEY,
  balance INTEGER DEFAULT 0,
  bank INTEGER DEFAULT 0,
  last_daily BIGINT DEFAULT 0,
  last_work BIGINT DEFAULT 0,
  last_rob BIGINT DEFAULT 0,
  rules_accepted INTEGER DEFAULT 0,
  partner_id TEXT,
  bio TEXT,
  marriage_time BIGINT,
  parent_id TEXT,
  children TEXT
);

-- 5. Inventory
CREATE TABLE IF NOT EXISTS inventory (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT,
  item_id TEXT,
  count INTEGER DEFAULT 0
);

-- 6. Giveaways
CREATE TABLE IF NOT EXISTS giveaways (
  message_id TEXT PRIMARY KEY,
  guild_id TEXT REFERENCES guild_configs(guild_id) ON DELETE CASCADE,
  channel_id TEXT,
  prize TEXT,
  winners INTEGER,
  end_time INTEGER,
  ended INTEGER DEFAULT 0
);

-- 7. Warns
CREATE TABLE IF NOT EXISTS warns (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  guild_id TEXT REFERENCES guild_configs(guild_id) ON DELETE CASCADE,
  user_id TEXT,
  reason TEXT,
  timestamp INTEGER
);

-- 8. AFK System (NEW)
CREATE TABLE IF NOT EXISTS afk (
  user_id TEXT PRIMARY KEY,
  reason TEXT DEFAULT 'AFK',
  timestamp BIGINT,
  guild_id TEXT
);

-- 9. Logs
CREATE TABLE IF NOT EXISTS logs (
  guild_id TEXT REFERENCES guild_configs(guild_id) ON DELETE CASCADE,
  event TEXT,
  channel_id TEXT,
  PRIMARY KEY (guild_id, event)
);

-- 10. Fake Permissions
CREATE TABLE IF NOT EXISTS fake_permissions (
  guild_id TEXT REFERENCES guild_configs(guild_id) ON DELETE CASCADE,
  role_id TEXT,
  permission TEXT,
  PRIMARY KEY (guild_id, role_id, permission)
);

-- 11. Custom Command Invokes
CREATE TABLE IF NOT EXISTS invokes (
  guild_id TEXT REFERENCES guild_configs(guild_id) ON DELETE CASCADE,
  command TEXT,
  message TEXT,
  PRIMARY KEY (guild_id, command)
);

-- 12. Aliases
CREATE TABLE IF NOT EXISTS aliases (
  guild_id TEXT REFERENCES guild_configs(guild_id) ON DELETE CASCADE,
  alias TEXT,
  command TEXT,
  PRIMARY KEY (guild_id, alias)
);

-- 13. AutoMod
CREATE TABLE IF NOT EXISTS automod (
  guild_id TEXT PRIMARY KEY REFERENCES guild_configs(guild_id) ON DELETE CASCADE,
  links INTEGER DEFAULT 0,
  invites INTEGER DEFAULT 0,
  mass_mentions INTEGER DEFAULT 0,
  bad_words INTEGER DEFAULT 0
);

-- 14. Reaction Roles
CREATE TABLE IF NOT EXISTS reaction_roles (
  message_id TEXT,
  guild_id TEXT REFERENCES guild_configs(guild_id) ON DELETE CASCADE,
  channel_id TEXT,
  emoji TEXT,
  role_id TEXT,
  PRIMARY KEY (message_id, emoji)
);
